global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'network-wrangler'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    
  - job_name: 'network-elements'
    static_configs:
      - targets: ['enodeb-1:161', 'gnodeb-1:161']
    scrape_interval: 30s
